name: "Check DVC GitHub Action"

on: [push]

jobs:
  check:
    strategy:
      matrix:
        runs-on: [ '{"runs-on": "ubuntu-latest"}', '{"runs-on": "macos-latest"}', '{"runs-on": "ubuntu-latest", "container": "ubuntu:18.04"}' ]
    runs-on: ${{ fromJSON(matrix.runs-on).runs-on }}
    container: ${{ fromJSON(matrix.runs-on).container }} 

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: "npm ci"
      run: npm ci

    - name: "lint"
      run: npm run lint

    - name: "tests"
      run: |
        npm run test

    - uses: iterative/dvc-action@v1.0.1
      with:
        version: '1.0.1'

    - name: "DVC test"
      run: |
        DVC_VER=$(dvc --version)
        if [ $DVC_VER != '1.0.1' ]; then
          exit 1
        fi

    - uses: iterative/dvc-action@v1.0.1
      with:
        version: latest
      
    - name: "DVC test"
      run: |
        DVC_VER=$(dvc --version)
        if [ $DVC_VER == '1.0.1' ]; then
          exit 1
        fi
