name: "Check DVC GitHub Action"

on: [push]

jobs:
  check:
    strategy:
      matrix:
        runs-on: [windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2

    - name: "npm ci"
      run: npm ci

    - name: "lint"
      run: npm run lint

    - name: "tests"
      run: |
        npm run test

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: iterative/dvc-action@v1.0.1
      with:
        version: '1.0.0'

    - name: "DVC test"
      run: |
        dvc version
        DVC_VER=$(dvc --version)
        if [ $DVC_VER != '1.0.0' ]; then
          exit 1
        fi

    - uses: iterative/dvc-action@v1.0.1
      with:
        version: latest
      
    - name: "DVC test"
      run: |
        dvc version
        DVC_VER=$(dvc --version)
        if [ $DVC_VER == '1.0.0' ]; then
          exit 1
        fi
