name: "Check DVC GitHub Action"

on: [push]

jobs:
  check:
    strategy:
      matrix:
        runs-on: [ '{"runs-on": "ubuntu-latest"}', 
          '{"runs-on": "macos-latest"}', 
          '{"runs-on": "ubuntu-latest", "container": "ubuntu:18.04"}',
          '{"runs-on": "windows-latest"}']

    runs-on: ${{ fromJSON(matrix.runs-on).runs-on }}
    container: ${{ fromJSON(matrix.runs-on).container }} 

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: iterative/setup-dvc@test-dvc

    - name: "DVC test"
      if: "!contains(fromJSON(matrix.runs-on).runs-on, 'windows')"
      run: |
        DVC_VER=$(dvc --version)

        if [ $DVC_VER == '1.0.1' ]; then
          exit 1
        fi
